### PR TITLE
UIX enhancements on disable/available dates

### PR DESCRIPTION
**Pull request by OzoTek**
After a few feedbacks, I noticed people had a hard time distinguishing disabled and available dates, so I've set some opacity on the disabled, increased the `fontWeight` on the available ones, and made the grey a little bit darker.

I also removed the default option that was disabling the dates that are not in the current month. It was confusing, I think this should be set at the developer's will from `isDateBlocked()`.
If needed I can add it back as a boolean prop with a default value, if you think it's relevant.

Last thing, I added an optional prop allowing a function to be passed to bind to the `onPress` when the date is disabled.
It seems relevant to me to inform the user of what's going on and why he can't select certain dates. My use case is simply pop an `Alert` when clicking on disabled, to explain why it's blocked, but it's up to the dev ;).

Here's how it looks now: 
screenshot_20170329-192829_01

Hope it works for you! 

Alex. C

### CODE REVIEW

**Comment by jirikolarik** [comment]
This is excellent, I'm glad that this is really used in production

**Comment by OzoTek** [comment]
Well it's the only lib I've tried that was really handling periods well, so nice job ;)

**Comment by OzoTek** [comment]
By the way it looks like you didn't push the release to `npm`, could you do it please ? It seems better than putting the git repo as a version :)

**Comment by jirikolarik** [comment]
There was no package.json version update, but hold on, that should be quick

**Comment by OzoTek** [comment]
Oh my bad then, thanks!

**Pull request merged**
