### PR TITLE
Add possibility to add custom styles

### PR DESCRIPTION
**Pull request by jirikolarik**
Now you can adjust styles by passing them as a parameter

```jsx
const styles = StyleSheet.create({
  calendar: {
    backgroundColor: 'rgb(0, 0, 0)'
  }
})

<Dates styles={styles} />
```

### CODE REVIEW

**Comment by iLeonelPerea** [comment]
someone can merge this pr?

**Comment by jirikolarik** [comment]
@iLeonelPerea does it work for you?

**Comment by thebiltheory** [comment]
2017? 😅

Is this still on?

**Comment by jirikolarik** [comment]
Merged, I hope it helps

**Pull request merged**
